### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by notxcain**

### CODE REVIEW

**Comment by SemanticBeeng** [comment]
hi Denis,

Please advise on `https://scalameta.org/paradise/` since it is not maintained anymore.

Any plans to move away from it?

**Comment by notxcain** [comment]
@SemanticBeeng unfortunately scalameta/paradise is EOL. Any suggestions regarding another implementations are highly appreciated.

**Comment by SemanticBeeng** [comment]
Also, I'd like to use such generated code to compile with `scalajs` to call from Ajax client applications.

http://frees.io/docs/core/algebras/
_"For each smart constructor def foo(x: X, y: Y, ...): FS[Z], the @free generates a case class Foo, whose fields are the parameters of the constructor. For those with a background in object-oriented design, this is similar to the Command Pattern."_

Do you see any reason why such generated code would not be compiling with `scalajs`?

**Comment by notxcain** [comment]
Superseded by #50

**Pull request closed without merging**
